title: Caroline Walter
logo: /assets/img/headshot_circular.png

description: Email: carowalter26@hotmail.com
description: Cell: (631)-624-5872
description: LinkedIn Profile: linkedin.com/in/caroline-walter-2a8592191
show_downloads: true
theme: jekyll-theme-minimal
