title: Caroline Walter
logo: /assets/img/headshot_circular.png

description: My name is Caroline Walter and I am a recent graduate from Tufts University.  I have powerful technical skills and enjoy digging into code or data to problem-solve, but I am also very personable and enjoy working with a team to create out-of-the-box answers for the most complex of problems. 
theme: jekyll-theme-minimal
